employee/urls.py
from django.urls import path
from .views import add_employee, remove_employee, update_employee

# app name.
app_name = 'employee'


# urlpatterns.
urlpatterns = [
    path('add/', add_employee, name='add_employee'),
    path('<int:pk>/remove', remove_employee, name='remove_employee'),
    path('<int:pk>/update/', update_employee, name='update_employee'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('employee/', include('employee.urls', namespace='employee')),
]

employee/models.py
from django.db import models

# Create your models here.

# Employee Model.
class Employee(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    
    def __str__(self):
        return str(self.first_name + ' ' + self.last_name)

    class Meta:
        db_table = ''
        managed = True
        verbose_name = 'Employee'
        verbose_name_plural = 'Employees'

employee/forms.py
from django import forms
from django.forms import widgets
from .models import Employee

class EmployeeForm(forms.ModelForm):
    first_name = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': 'btn btn-success border border-light text-left',
                # 'id':'first_name'
                'placeholder': 'Your First Name'
            }
        )
    )
    last_name = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': 'btn btn-success border border-light text-left',
                'placeholder': 'Your Last Name'
            }
        )
    )
    
    class Meta:
        model = Employee
        fields = ('first_name', 'last_name')

employee/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, JsonResponse
from django.contrib import messages
from .forms import EmployeeForm
from .models import Employee
# Create your views here.




def add_employee(request):
    employees = Employee.objects.all().order_by('first_name')
    form = EmployeeForm()
    if request.method == 'POST':
        form = EmployeeForm(request.POST)
        if form.is_valid():
            form.save()
            form = EmployeeForm()
    context = {
        'form': form,
        'employees': employees,
        'dev': 'Mohammed Elkhamlichi'
    }
    return render(request, 'add_employee.html', context)




def remove_employee(request, pk):
    employee = get_object_or_404(Employee, pk=pk)
    if request.method == 'POST':
        employee.delete()
        messages.success(request, 'employee has been deleted')
        return redirect('employee:add_employee')


    context = {"employee": employee}
    return render(request, 'remove_employee.html', context)




def update_employee(request, pk):
    employee = get_object_or_404(Employee, pk=pk)
    form = EmployeeForm(instance=employee)
    if request.method == 'POST':
        form = EmployeeForm(request.POST, instance=employee)
        if form.is_valid():
            form.save()
            messages.success(request, 'Employee has been updated')
            return redirect('employee:add_employee')
            
    context = {"form":form}

    return render(request, 'update_employee.html', context)

employee/templates/add_employee.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- bootstrap css files -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>Employee</title>
</head>

<body>
    <div class="container mt-5">
        <form class="m-auto w-100 bg-info text-center p-3 rounded" id="form" method="POST">
            {% csrf_token %}
            <h1 class="mb-5">Employees Management</h1>
            {% if messages %}
                {% for message in messages %}
                    <center>
                        <p class="bg-{{message.tags}} border w-50 text-center p-2 mt-3 m-3 rounded">
                        {{ message }}
                    </p>
                    </center>
                {% endfor %}
            {% endif %}
            
            {{ form.as_p }}
            <input type="submit" value="Add Employee" id="add" class="btn btn-success m-auto border">
        </form>
        <h2 class="p-2 mt-3 mr-3 bg-info w-100 rounded">Employees List</h2>
        <table class="table table-striped mt-3 rounded">
            <thead class="thead-dark">
                <tr>
                    <th>ID</th>
                    <th>First Name</th>
                    <th>Last Name</th>
                    <th>Remove</th>
                    <th>Update</th>
                </tr>
            </thead>
            <tbody>
                {% for employee in employees %}
                <tr>
                    <td>{{ employee.id }}</td>
                    <td>{{ employee.first_name }}</td>
                    <td>{{ employee.last_name }}</td> 
                    <td><a class="btn btn-danger" href="{% url 'employee:remove_employee' employee.id %}">Remove</td>
                    <td class="btn-update"><a class="btn btn-info" href="{% url 'employee:update_employee' employee.id %}">Update</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <!-- javascript files -->
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <!-- <script src="{% static 'js/add_employee.js' %}"></script> -->
</body>
</html>

employee/templates/remove_employee.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- bootstrap css files -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>Employee</title>
</head>

<body>
    
    <div class="container mt-5">
        <form class="m-auto w-100 bg-info text-center p-3 rounded" id="form" method="POST">
            {% csrf_token %}
            <h1 class="mb-5">Employees Management</h1>
            <figure>Are  you sure you want to remove <span class="text-light">{{ employee.first_name }}</span></figure>
            <a class="btn btn-success" href="{% url 'employee:add_employee' %}">Cancel</a>
            <input type="submit" value="Remove" class="btn btn-danger">
        </form>
      
    </div>

    <!-- javascript files -->
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="{% static 'js/add_employee.js' %}"></script>

</body>
</html>

employee/templates/update_employee.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- bootstrap css files -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>Employee</title>
</head>

<body>
    
    <div class="container mt-5">
        <form class="m-auto w-100 bg-info text-center p-3 rounded" id="form" method="POST">
            {% csrf_token %}
            <h1 class="mb-5">Employees Management</h1>
            {{ form.as_p }}
            <input type="submit" value="Update Employee info" id="add" class="btn btn-success m-auto border">
        </form>
    </div>

    <!-- javascript files -->
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <!-- <script src="{% static 'js/add_employee.js' %}"></script> -->
</body>
</html>